package:
  name: nss-cos7-x86_64
  version: 3.44.0

source:
  - url: {{ x86_url }}/nss-3.44.0-7.el7_7.x86_64.rpm
    sha256: 76e4a0944647a345ea932e8d79058f9856e05895528f8b0596eb9099a7772f22
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-softokn-cos7-x86_64 >=3.44.0
    - nss-util-cos7-x86_64 >=3.44.0
  host:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-softokn-cos7-x86_64 >=3.44.0
    - nss-util-cos7-x86_64 >=3.44.0
  run:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-softokn-cos7-x86_64 >=3.44.0
    - nss-util-cos7-x86_64 >=3.44.0

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Network Security Services
  description: |
    Network Security Services (NSS) is a set of libraries designed to support
    cross-platform development of security-enabled client and server applications.
    Applications built with NSS can support SSL v2 and v3, TLS, PKCS #5, PKCS #7,
    PKCS #11, PKCS #12, S/MIME, X.509 v3 certificates, and other security
    standards.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
