package:
  name: copy-jdk-configs-cos7-s390x
  version: 3.3

source:
  - url: {{ clefos7_url }}/noarch/copy-jdk-configs-3.3-10.el7_5.noarch.rpm
    sha256: 21a07db923108cc57a7a0e9b2a60626a65ccef0adf964b9e3b28f5dc7731ff88
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: https://pagure.io/copy_jdk_configs
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: "(CDT) JDKs configuration files copier"
  description: |
        Utility script to transfer JDKs configuration files between updates or for
        archiving. With script to fix incorrectly created rpmnew files

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
