package:
  name: nspr-cos6-x86_64
  version: 4.19.0

source:
  - url: http://mirror.centos.org/centos-6/6/os/x86_64/Packages/nspr-4.19.0-1.el6.i686.rpm
    sha256: ab4b72a2833cc6cd1c15cde6c73ded3e6db8646868cbc62949c8478e1ef4bb11
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/nspr/
  license: MPL-2.0
  license_family: Other
  license_file: nspr-license
  summary: (CDT) Netscape Portable Runtime
  description: |
    NSPR provides platform independence for non-GUI operating system facilities.
    These facilities include threads, thread synchronization, normal file and
    network I/O, interval timing and calendar time, basic memory management
    (malloc and free) and shared library linking.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

