package:
  name: tzdata-java-cos7-s390x 
  version: 2020a 

source:
  - url: {{ clefos7_url }}/noarch/tzdata-java-2020a-1.el7.noarch.rpm
    sha256: 5a1b71afd53163f8932f500643b7fd87b3a611d0e733827b91d801d583d541f1 
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 3
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: openjdk-license
  summary: (CDT) OpenJDK Runtime Environment
  description: |
    The OpenJDK runtime environment.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
