package:
  name: tzdata-java-cos7-ppc64le
  version: 2019c

source:
  - url: http://mirror.centos.org/altarch/7.8.2003/os/ppc64le/Packages/tzdata-java-2019c-1.el7.noarch.rpm
    sha256: ef0c0ac7183772b70ee519f5b9c4664f37edd34d991abe4bf3c267d88cc4c253
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: openjdk-license
  summary: (CDT) OpenJDK Runtime Environment
  description: |
    The OpenJDK runtime environment.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
