package:
  name: zip-cos7-s390x
  version: 3.0

source:
  - url: {{ clefos7_url }}/s390x/zip-3.0-11.el7.s390x.rpm
  - sha256: 3e75f6814f3b490a36397c5f4ca0429bbf86423fb57ea458fdcbc1490507585d
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.info-zip.org/Zip.html
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: (CDT) A file compression and packaging utility compatible with PKZIP
  description: |
        'The zip program is a compression and file packaging utility.  Zip is analogous

        to a combination of the UNIX tar and compress commands and is compatible with

        PKZIP (a compression and file packaging utility for MS-DOS systems).  Install

        the zip package if you need to compress files using the zip program.

        '
extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
