package:
  name: nss-softokn-freebl-cos7-x86_64
  version: 3.44.0

source:
  - url: {{ x86_url }}/nss-softokn-freebl-3.44.0-8.el7_7.x86_64.rpm
    sha256: 9949831b67f6eb68dc9df6df3e4570bd5f9301de3c7d67c41512fcaaadb40da5
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-util-cos7-x86_64 >=3.44.0
  host:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-util-cos7-x86_64 >=3.44.0
  run:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-util-cos7-x86_64 >=3.44.0

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Freebl library for the Network Security Services
  description: |
    NSS Softoken Cryptographic Module Freebl Library  Install the nss-softokn-
    freebl package if you need the freebl library.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
