package:
  name: java-1.8.0-openjdk-headless-cos6-x86_64
  version: 1.8.0.171

source:
  - url: http://mirror.centos.org/centos-6/6/os/x86_64/Packages/java-1.8.0-openjdk-headless-1.8.0.171-8.b10.el6_9.x86_64.rpm
    sha256: 7b59c90f22dd00d72be06b476f4edaa1837d9a9fb3f43500aec2415964cfea6b
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - chkconfig-cos6-x86_64 >=1.3
    - copy-jdk-configs-cos6-x86_64 >=3.3
    - nss-cos6-x86_64 >=3.14.3
    - nss-softokn-cos6-x86_64 >=3.14.3
    - tzdata-java-cos6-x86_64 >=2008e
    - ca-certificates-cos6-x86_64 >=2016.2.10
  host:
    - chkconfig-cos6-x86_64 >=1.3
    - copy-jdk-configs-cos6-x86_64 >=3.3
    - nss-cos6-x86_64 >=3.14.3
    - nss-softokn-cos6-x86_64 >=3.14.3
    - tzdata-java-cos6-x86_64 >=2008e
    - ca-certificates-cos6-x86_64 >=2016.2.10
  run:
    - chkconfig-cos6-x86_64 >=1.3
    - copy-jdk-configs-cos6-x86_64 >=3.3
    - nss-cos6-x86_64 >=3.14.3
    - nss-softokn-cos6-x86_64 >=3.14.3
    - tzdata-java-cos6-x86_64 >=2008e
    - ca-certificates-cos6-x86_64 >=2016.2.10

test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: openjdk-license
  summary: "(CDT) The OpenJDK runtime environment without audio and video support"
  description: |
        The OpenJDK runtime environment without audio and video

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
