package:
  name: nss-softokn-cos6-x86_64
  version: 3.14.3

source:
  - url: http://mirror.centos.org/centos-6/6/os/x86_64/Packages/nss-softokn-3.14.3-23.3.el6_8.x86_64.rpm
    sha256: 7e4298904daec41067f01c8943055560cd153d1f39c668c6d2fa978a3d66dd81
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-softokn-freebl-cos6-x86_64 >=3.14.3
    - nss-util-cos6-x86_64 >=3.36.0
  host:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-softokn-freebl-cos6-x86_64 >=3.14.3
    - nss-util-cos6-x86_64 >=3.36.0
  run:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-softokn-freebl-cos6-x86_64 >=3.14.3
    - nss-util-cos6-x86_64 >=3.36.0

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Network Security Services Softoken Module
  description: |
    Network Security Services Softoken Cryptographic Module

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

