package:
  name: nss-cos6-x86_64
  version: 3.36.0

source:
  - url: {{ centos6_url }}/nss-3.36.0-8.el6.x86_64.rpm
    sha256: 7e2ada2dbb795a56a2961d0ea681d47f481c42faf3cd0886d991bf07f8d3c39a
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 2
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-softokn-cos6-x86_64 >=3.14.0
    - nss-util-cos6-x86_64 >=3.36.0
  host:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-softokn-cos6-x86_64 >=3.14.0
    - nss-util-cos6-x86_64 >=3.36.0
  run:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-softokn-cos6-x86_64 >=3.14.0
    - nss-util-cos6-x86_64 >=3.36.0

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Network Security Services
  description: |
    Network Security Services (NSS) is a set of libraries designed to support
    cross-platform development of security-enabled client and server applications.
    Applications built with NSS can support SSL v2 and v3, TLS, PKCS #5, PKCS #7,
    PKCS #11, PKCS #12, S/MIME, X.509 v3 certificates, and other security
    standards.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
