package:
  name: nss-softokn-freebl-cos6-x86_64
  version: 3.14.3

source:
  - url: {{ centos6_url }}/nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64.rpm
    sha256: bccc1e55c5cf90d7ee5ef2d25253fc8dd2c3854121a65711f5f5618b097ffb70
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 2
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-util-cos6-x86_64 >=3.14.3
  host:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-util-cos6-x86_64 >=3.14.3
  run:
    - nspr-cos6-x86_64 >=4.19.0
    - nss-util-cos6-x86_64 >=3.14.3

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Freebl library for the Network Security Services
  description: |
    NSS Softoken Cryptographic Module Freebl Library  Install the nss-softokn-
    freebl package if you need the freebl library.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
