recipes:
  - name: zip-cos7-ppc64le                            #[ppc64le]
    path: zip-cos7-ppc64le                            #[ppc64le]

  - name: tzdata-java-cos7-ppc64le                    #[ppc64le]
    path: tzdata-java-cos7-ppc64le                    #[ppc64le]

  - name: java-11-openjdk-headless-cos7-ppc64le       #[ppc64le]
    path: java-11-openjdk-headless-cos7-ppc64le       #[ppc64le]

  - name: java-11-openjdk-cos7-ppc64le                #[ppc64le]
    path: java-11-openjdk-cos7-ppc64le                #[ppc64le]

  - name: java-11-openjdk-devel-cos7-ppc64le          #[ppc64le]
    path: java-11-openjdk-devel-cos7-ppc64le          #[ppc64le]

  - name: tzdata-java-cos7-x86_64                     #[x86_64]
    path: tzdata-java-cos7-x86_64                     #[x86_64]

  - name: chkconfig-cos7-x86_64                       #[x86_64]
    path: chkconfig-cos7-x86_64                       #[x86_64]

  - name: nss-util-cos7-x86_64                        #[x86_64]
    path: nss-util-cos7-x86_64                        #[x86_64]

  - name: nss-cos7-x86_64                             #[x86_64]
    path: nss-cos7-x86_64                             #[x86_64]

  - name: nspr-cos7-x86_64                            #[x86_64]
    path: nspr-cos7-x86_64                            #[x86_64]

  - name: nss-softokn-freebl-cos7-x86_64              #[x86_64]
    path: nss-softokn-freebl-cos7-x86_64              #[x86_64]

  - name: nss-softokn-cos7-x86_64                     #[x86_64]
    path: nss-softokn-cos7-x86_64                     #[x86_64]

  - name: copy-jdk-configs-cos7-x86_64                #[x86_64]
    path: copy-jdk-configs-cos7-x86_64                #[x86_64]

  - name: java-11-openjdk-headless-cos7-x86_64        #[x86_64]
    path: java-11-openjdk-headless-cos7-x86_64        #[x86_64]

  - name: java-11-openjdk-cos7-x86_64                 #[x86_64]
    path: java-11-openjdk-cos7-x86_64                 #[x86_64]

  - name: java-11-openjdk-devel-cos7-x86_64           #[x86_64]
    path: java-11-openjdk-devel-cos7-x86_64           #[x86_64]

 -  name: tzdata-java-cos7-s390x                      #[s390x]
    path: tzdata-java-cos7-s390x                      #[s390x]

 -  name: chkconfig-cos7-s390x                        #[s390x]
    path: chkconfig-cos7-s390x                        #[s390x]

 -  name: copy-jdk-configs-cos7-s390x                 #[s390x]
    path: copy-jdk-configs-cos7-s390x                 #[s390x]

 -  name: java-1.8.0-openjdk-headless-cos7-s390x      #[s390x]
    path: java-1.8.0-openjdk-headless-cos7-s390x      #[s390x]

 -  name: java-1.8.0-openjdk-cos7-s390x               #[s390x]
    path: java-1.8.0-openjdk-cos7-s390x               #[s390x]

 -  name: java-1.8.0-openjdk-devel-cos7-s390x         #[s390x]
    path: java-1.8.0-openjdk-devel-cos7-s390x         #[s390x]

 -  name: zip-cos7-s390x                              #[s390x]
    path: zip-cos7-s390x                              #[s390x]