ppc_url:
  - https://vault.centos.org/altarch/7.8.2003/os/ppc64le/Packages/
x86_url:
  - https://rpmfind.net/linux/centos/7.9.2009/os/x86_64/Packages
clefos7_url:
  - https://download.sinenomine.net/clefos/7/os/
