package:
  name: nss-util-cos7-x86_64
  version: 3.44.0

source:
  - url: {{ x86_url }}/nss-util-3.44.0-4.el7_7.x86_64.rpm
    sha256: 401b5322ea4d54d259a1947a92417671831bc17adbcbf487e7b52eda793ff457
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos7-x86_64 >=4.21.0
  host:
    - nspr-cos7-x86_64 >=4.21.0
  run:
    - nspr-cos7-x86_64 >=4.21.0

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Network Security Services Utilities Library
  description: |
    Utilities for Network Security Services and the Softoken module

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

