package:
  name: chkconfig-cos6-x86_64
  version: 1.3.49.5

source:
  - url: http://mirror.centos.org/centos-6/6/os/x86_64/Packages/chkconfig-1.3.49.5-1.el6.x86_64.rpm
    sha256: 78386af88e956364b220b3ef9fb268c7cf83ec1e8b763e65ae1cf71d4d4cc9dd
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: False
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: https://github.com/fedora-sysv/chkconfig
  license: GPL-2.0-only
  license_family: GPL2
  license_file: {{ SRC_DIR }}/binary/usr/share/doc/chkconfig-1.3.49.5/COPYING
  summary: "(CDT) A system tool for maintaining the /etc/rc*.d hierarchy"
  description: |
        Chkconfig is a basic system utility.  It updates and queries runlevel
        information for system services.  Chkconfig manipulates the numerous symbolic
        links in /etc/rc.d, to relieve system administrators of some of the drudgery
        of manually editing the symbolic links.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

