package:
  name: java-1.8.0-openjdk-devel-cos7-s390x
  version: 1.8.0.262.b10

source:
  - url: http://download.sinenomine.net/clefos/7/os/s390x/java-1.8.0-openjdk-devel-1.8.0.262.b10-1.el7.s390x.rpm
    sha256: 7f0ee7bc39ea62d0e9a7375719870289e85181228b65949cbebc0db0a8cc9c39
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - java-1.8.0-openjdk-cos7-s390x          ==1.8.0.262.b10
    - java-1.8.0-openjdk-headless-cos7-s390x ==1.8.0.262.b10
  host:
    - java-1.8.0-openjdk-cos7-s390x          ==1.8.0.262.b10
    - java-1.8.0-openjdk-headless-cos7-s390x ==1.8.0.262.b10
  run:
    - java-1.8.0-openjdk-cos7-s390x          ==1.8.0.262.b10
    - java-1.8.0-openjdk-headless-cos7-s390x ==1.8.0.262.b10

test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: openjdk-license
  summary: (CDT) OpenJDK Development Toolkit
  description: |
    The OpenJDK Development Toolkit.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

