package:
  name: tzdata-java-cos6-x86_64
  version: 2018e

source:
  - url: {{ centos6_url }}/tzdata-java-2018e-3.el6.noarch.rpm
    sha256: cb1e4abf1981101afc2a87b1a434068d65e5f2828846bbc051199fda58002bd6
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 2
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

test:
  commands:
    - echo "it installs!"

about:
  home: http://openjdk.java.net/
  license: ASL 1.1 and ASL 2.0 and BSD and BSD with advertising and GPL+ and GPLv2 and GPLv2 with exceptions and IJG and LGPLv2+ and MIT and MPLv1.1 and MPLv2.0 and Public Domain and W3C and zlib
  license_family: GPL2
  license_file: openjdk-license
  summary: (CDT) OpenJDK Runtime Environment
  description: |
    The OpenJDK runtime environment.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
