package:
  name: nss-softokn-cos7-x86_64
  version: 3.44.0

source:
  - url: {{ x86_url }}/nss-softokn-3.44.0-8.el7_7.x86_64.rpm
    sha256: f8d10e879c3bc46ad909f632da2cbb59407afaf1374af36dd268c5d213771905
    no_hoist: true
    folder: binary
  - path: ../common_files

build:
  number: 1
  noarch: generic
  binary_relocation: false
  detect_binary_files_with_prefix: false
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-softokn-freebl-cos7-x86_64 >=3.44
    - nss-util-cos7-x86_64 >=3.44.0
  host:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-softokn-freebl-cos7-x86_64 >=3.44
    - nss-util-cos7-x86_64 >=3.44.0
  run:
    - nspr-cos7-x86_64 >=4.21.0
    - nss-softokn-freebl-cos7-x86_64 >=3.44
    - nss-util-cos7-x86_64 >=3.44.0

test:
  commands:
    - echo "it installs!"

about:
  home: http://www.mozilla.org/projects/security/pki/nss/
  license: MPL-2.0
  license_family: Other
  license_file: nss-license
  summary: (CDT) Network Security Services Softoken Module
  description: |
    Network Security Services Softoken Cryptographic Module

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team

